image: nikolaik/python3.7-nodejs12 
stages:
  - install
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}}
  paths:
    - node_modules/
    - layers/nodejs/node_modules/


install:
  stage: install
  script:
    - npm ci
    - cd layers/nodejs
    - npm ci
    - cd ../..

test:
  stage: test
  script:
    - npm run test
  coverage: '/Code coverage: \d+\.\d+/'

deploy:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install aws-sam-cli
  script:
    - sam package --template-file template.yaml --output-template-file deploy.yaml --s3-bucket sharin-serverless --region us-east-1 
    - sam deploy --template-file /home/nce/Projects/sharin-serverless/sharin-auth/deploy.yaml --stack-name SharinServerless --capabilities CAPABILITY_IAM --region us-east-1
  only:
    - master
  when: manual

